myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
     re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homePage),
    path('about/', views.aboutPage),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myProject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.posts_page, name='page'),
]

myProject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

myProject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title

myProject/users/models.py
from django.db import models

# Create your models here.

myProject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

myProject/myProject/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def homePage(request):
    # return HttpResponse('Hello, World! This is the homepage of myProject.')
    return render(request, 'home.html')


def aboutPage(request):
    # return HttpResponse('This is the about page of myProject.')
    return render(request, 'about.html')

myProject/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def posts_page(request, slug):
    # return HttpResponse(slug)
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/posts_page.html', {'post': post})

@login_required(login_url='/users/login/')
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save with user
            newPost = form.save(commit=False)
            newPost.author = request.user
            newPost.save()
            return redirect('posts:list')
    else : 
        form = forms.CreatePost()
        
    return render(request, 'posts/posts_new.html', {'form': form})

myProject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Register view
def register_view(request):
    # Save the form data if the form is valid
    if request.method == 'POST': 
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('posts:list') 
    else:
        # UserCreationForm is a built-in form in Django
        form = UserCreationForm()
    
    # return the form to the template
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #! Log the user in
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list') 
    else:
        form = AuthenticationForm()
        
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

myProject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %} 
{% block title %} 
  Posts 
{% endblock %} 

{% block content %}
  <section>
    <h1>Posts</h1>

    {% for post in posts %}

      <article class="post">
        <h2>
          <a href="{% url 'posts:page' slug=post.slug %}">
            {{ post.title }}
          </a>
        </h2>
        <p>{{ post.date }} by {{ post.author }}</p>
        <p>{{ post.body }}</p>
      </article>

    {% endfor %}
  </section>
{% endblock %}

myProject/posts/templates/posts/posts_new.html
{% extends 'layout.html' %} 
{% block title %} 
    New Post
{% endblock %} 

{% block content %}
  <section>
    <h1>New Post</h1>
    <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="form-submit">Add Post</button>
    </form>
  </section>
{% endblock %}

myProject/posts/templates/posts/posts_page.html
{% extends 'layout.html' %} 
{% block title %} 
{{ post.title }} 
{% endblock %} 

{% block content %}
  <section>
    <img 
      class="banner"
      src="{{ post.banner.url }}" 
      alt="{{ post.title }}"
    />
    <h1>{{ post.title }}</h1>
    <p>{{ post.date }}</p>
    <p>{{ post.body }}</p>
  </section>
{% endblock %}

myProject/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>About</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <h1>About</h1>

    <p>
      <a href="/">Home</a>
    </p>
  </body>
</html>

myProject/templates/home.html
{% extends 'layout.html' %} 
{% block title %} Home {% endblock %} 
{% block content %}
<h1>Welcome to my Project</h1>
<p>
  This is a simple project to demonstrate how to use Flask with Jinja2
  templates.
</p>

{% endblock %}

myProject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">
        <span role='img' aria-label='Home' title="Home">🏠</span>
      </a> | 
      <a href="/about">
        <span role='img' aria-label='About' title="About">😊</span>
      </a> | 
      <a href="{% url 'posts:list' %}">
        <span role='img' aria-label='Post' title="Post">📰</span>
      </a> | 
     
      {% if user.is_authenticated %}
        <a href="{% url 'posts:new-post' %}" title="New Post">
          <span role='img' aria-label='New Post'>📝</span>
        </a> | 
        <form class='logout' action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button class="logout-button" title="Logout">
            <span role='img' aria-label='Logout' title="Logout">👋</span>
          </button>
        </form>
      {% else %}
        <a href="{% url 'users:register' %}" title="Register">
          <span role='img' aria-label='Register'>🚀</span>
        </a> | 
        <a href="{% url 'users:login' %}" title="Login">
          <span role='img' aria-label='Login'>🔐</span>
        </a>
      {% endif %}
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

myProject/users/templates/users/login.html
{% extends 'layout.html' %} 
{% block title %} 
  Login
{% endblock %} 

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'users:login' %}" method="post" class="form-with-validation">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <button>Login</button>
  </form>
{% endblock %}

myProject/users/templates/users/register.html
{% extends 'layout.html' %} 
{% block title %} 
  Register a new user
{% endblock %} 

{% block content %}
  <h1>Register</h1>
  <form action="{% url 'users:register' %}" method="post" class="form-with-validation">
    {% csrf_token %}
    {{ form }}
    <button>Register</button>
  </form>
{% endblock %}